
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: fitlink_development

test:
  <<: *default
  database: fitlink_test

production:
  <<: *default
  database: fitlink_production